[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  madhephaestus/ESP32Servo @ ^3.0.5
  adafruit/Adafruit VL53L1X @ ^3.1.0
  adafruit/DHT sensor library @ ^1.4.6
  adafruit/Adafruit Unified Sensor @ ^1.1.14
  adafruit/Adafruit INA219 @ ^1.2.3
