import os
import pandas as pd
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
import m2cgen as m2c

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DAY2_CSV = os.path.join(BASE_DIR, "datasets", "day2_combined.csv")
DAY1_CSV = os.path.join(BASE_DIR, "raw_dataset.csv")
OUTPUT_PATH = os.path.join(BASE_DIR, "esp32_inference", "model_inference.h")

FEATURES = ['tof_mm', 'pan_deg', 'tilt_deg', 'signal_rate_kcps', 'ambient_rate_kcps', 'env_temp_C']
TARGET = 'residual_error_mm'

def load_data():
    # Load Day 2
    df2 = pd.read_csv(DAY2_CSV)
    df2['day'] = 2
    
    # Load Day 1
    df1 = pd.read_csv(DAY1_CSV, low_memory=False)
    rename_map = {
        'raw_distance_mm': 'tof_mm',
        'pan_calibrated_deg': 'pan_deg',
        'tilt_calibrated_deg': 'tilt_deg',
        'temperature_C': 'env_temp_C',
    }
    df1 = df1.rename(columns=rename_map)
    df1['day'] = 1
    
    if 'valid_return' not in df1.columns:
        df1['valid_return'] = (df1['tof_mm'] > 0).astype(int)
    if 'residual_error_mm' not in df1.columns and 'gt_distance_mm' in df1.columns:
        df1['residual_error_mm'] = df1['gt_distance_mm'] - df1['tof_mm']
        
    df = pd.concat([df1, df2], ignore_index=True)
    
    # Fill missing telemetry for Day 1 with 0 (since it was constant/broken)
    if 'signal_rate_kcps' in df.columns:
        df['signal_rate_kcps'] = df['signal_rate_kcps'].fillna(0)
    if 'ambient_rate_kcps' in df.columns:
        df['ambient_rate_kcps'] = df['ambient_rate_kcps'].fillna(0)
        
    trainable = df[(df['valid_return'] == 1) & (df['residual_error_mm'].notna())].dropna(subset=FEATURES + [TARGET])
    return trainable

def main():
    print("Loading data...")
    trainable = load_data()
    
    X = trainable[FEATURES]
    y = trainable[TARGET]
    
    print(f"Total trainable rows: {len(X)}")
    
    # CRITICAL FIX: Proper Train/Test split to avoid reporting training error
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    best_mae = float('inf')
    best_code = ""

    for depth in [10, 12, 15]:
        model = DecisionTreeRegressor(max_depth=depth, random_state=42)
        model.fit(X_train, y_train)
        preds = model.predict(X_test)
        mae = mean_absolute_error(y_test, preds)
        
        # Test export size
        code = m2c.export_to_c(model)
        size_kb = len(code) / 1024
        print(f"Depth {depth} | MAE: {mae:.2f} mm | Size: {size_kb:.1f} KB")
        
        if depth == 12:
            best_code = code
            best_mae = mae

    c_header = f"""
// Auto-generated by m2cgen
// Decision Tree (Depth 12, Test MAE: {best_mae:.2f} mm)

#ifndef MODEL_INFERENCE_H
#define MODEL_INFERENCE_H

{best_code}

#endif // MODEL_INFERENCE_H
"""
    with open(OUTPUT_PATH, 'w') as f:
        f.write(c_header)
        
    print(f"\nExported Depth 12 model to {OUTPUT_PATH}")

if __name__ == "__main__":
    main()
