#ifndef MODEL_INFERENCE_H
#define MODEL_INFERENCE_H

#ifdef __cplusplus
extern "C" {
#endif

// The ML Model generated by m2cgen
double score(double * input);

#ifdef __cplusplus
}
#endif

#endif // MODEL_INFERENCE_H
